/* This file is generated by genxml. */
/* No manual modification is permitted. */

#pragma once







class CResultLoader
{
public:
    struct STResult
    {
        STResult()
        {
            
        }
        
        struct STEnum
        {
            STEnum()
            {
                
                m_strcomment.clear();
                
                m_strname.clear();
                
            }
            
            stringc m_strcomment;
            
            stringc m_strname;
            
            struct STMember
            {
                STMember()
                {
                    
                    m_strcomment.clear();
                    
                    m_strname.clear();
                    
                    m_itype = 0;
                    
                }
                
                stringc m_strcomment;
                
                stringc m_strname;
                
                int32_t m_itype;
                

            };
            
            enum {ENM_Member_Num = 5};
            farray<STMember, ENM_Member_Num> m_vecSTMember;

        };
        
        enum {ENM_Enum_Num = 2};
        farray<STEnum, ENM_Enum_Num> m_vecSTEnum;
        struct STStruct
        {
            STStruct()
            {
                
                m_strcomment.clear();
                
                m_strname.clear();
                
            }
            
            stringc m_strcomment;
            
            stringc m_strname;
            
            struct STMember
            {
                STMember()
                {
                    
                    m_strcomment.clear();
                    
                    m_strname.clear();
                    
                    m_strtype.clear();
                    
                }
                
                stringc m_strcomment;
                
                stringc m_strname;
                
                stringc m_strtype;
                

            };
            
            enum {ENM_Member_Num = 2};
            farray<STMember, ENM_Member_Num> m_vecSTMember;

        };
        
        enum {ENM_Struct_Num = 8};
        farray<STStruct, ENM_Struct_Num> m_vecSTStruct;

    };
    
    const STResult & GetResult()
    {
        return m_STResult;
    }
    
    bool LoadCfg(const stringc & file)
	{
		TiXmlDocument document;
		if (!document.LoadFile((const char*)file.c_str()))
		{
			LOG_ERROR("CResultLoader::LoadCfg(%s) failed", (const char*)file.c_str());
			return false;
		}
		
		TiXmlElement* pResult = document.RootElement();
		if (!pResult)
		{
			LOG_ERROR("document.RootElement failed");
			return false;
		}
		
		// clear
		STResult tmp;
		m_STResult = tmp;
		
		
		
		
		for (TiXmlNode * pEnum = pResult->FirstChild("Enum"); NULL != pEnum; pEnum = pEnum->NextSibling("Enum"))
		{
			
            STResult::STEnum tmpEnum;
            
            tmpEnum.m_strcomment = ((TiXmlElement *)pEnum)->Attribute("comment");
            LOG_DEBUG("        comment %s", tmpEnum.m_strcomment.c_str());
            
            tmpEnum.m_strname = ((TiXmlElement *)pEnum)->Attribute("name");
            LOG_DEBUG("        name %s", tmpEnum.m_strname.c_str());
            
            
            for (TiXmlNode * pMember = pEnum->FirstChild("Member"); NULL != pMember; pMember = pMember->NextSibling("Member"))
            {
            
                STResult::STEnum::STMember tmpMember;
                
                tmpMember.m_strcomment = ((TiXmlElement *)pMember)->Attribute("comment");
                LOG_DEBUG("            comment %s", tmpMember.m_strcomment.c_str());
                
                tmpMember.m_strname = ((TiXmlElement *)pMember)->Attribute("name");
                LOG_DEBUG("            name %s", tmpMember.m_strname.c_str());
                
                ((TiXmlElement *)pMember)->Attribute("type", &tmpMember.m_itype);
                LOG_DEBUG("            type %d", tmpMember.m_itype);
                
                

                tmpEnum.m_vecSTMember.push_back(tmpMember);
            }

			m_STResult.m_vecSTEnum.push_back(tmpEnum);
		}
		for (TiXmlNode * pStruct = pResult->FirstChild("Struct"); NULL != pStruct; pStruct = pStruct->NextSibling("Struct"))
		{
			
            STResult::STStruct tmpStruct;
            
            tmpStruct.m_strcomment = ((TiXmlElement *)pStruct)->Attribute("comment");
            LOG_DEBUG("        comment %s", tmpStruct.m_strcomment.c_str());
            
            tmpStruct.m_strname = ((TiXmlElement *)pStruct)->Attribute("name");
            LOG_DEBUG("        name %s", tmpStruct.m_strname.c_str());
            
            
            for (TiXmlNode * pMember = pStruct->FirstChild("Member"); NULL != pMember; pMember = pMember->NextSibling("Member"))
            {
            
                STResult::STStruct::STMember tmpMember;
                
                tmpMember.m_strcomment = ((TiXmlElement *)pMember)->Attribute("comment");
                LOG_DEBUG("            comment %s", tmpMember.m_strcomment.c_str());
                
                tmpMember.m_strname = ((TiXmlElement *)pMember)->Attribute("name");
                LOG_DEBUG("            name %s", tmpMember.m_strname.c_str());
                
                tmpMember.m_strtype = ((TiXmlElement *)pMember)->Attribute("type");
                LOG_DEBUG("            type %s", tmpMember.m_strtype.c_str());
                
                

                tmpStruct.m_vecSTMember.push_back(tmpMember);
            }

			m_STResult.m_vecSTStruct.push_back(tmpStruct);
		}
		
		return true;
	}
    
private:
    STResult m_STResult;
};


